name: CI
on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: ðŸ”Ž Type check
        run: pnpm typecheck

  deploy-status:
    runs-on: ubuntu-latest
    needs: [typecheck]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
