name: 🚀 Cleanup (preview)
env:
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  PLANETSCALE_ORG: ${{ secrets.PLANETSCALE_ORG }}
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}

on:
  pull_request:
    types: [closed]

jobs:
  Cleanup-Preview:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: Install Pscale CLI
        run: brew install planetscale/tap/pscale
      - name: Deploy preview
        run: pnpm run script deploy-preview
